name: Docker CI/CD Pipeline
on:
  push:
    branches: [ "DockerFile_for_lab_2", "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ ivanmoroz070707/Simple-Lesons-for-Postmodern-Technologies-in-Software-Development- }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Важно для загрузки образа в ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase image name
        run: |
          echo "IMAGE=${{ env.REGISTRY }}/$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE }}:${{ github.sha }} .
          docker push ${{ env.IMAGE }}:${{ github.sha }}
  test:
    needs: build-and-push 
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase image name
      run: |
        echo "IMAGE=${{ env.REGISTRY }}/$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Pull Docker image
      run: docker pull ${{ env.IMAGE }}:${{ github.sha }}

    - name: Run tests inside container
      
      run: docker run ${{ env.IMAGE }}:${{ github.sha }} python -m unittest discover
